services:
  - type: web
    name: flask-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -b 0.0.0.0:5000 app:app"

    envVars:
      - key: HUGGINGFACEHUB_API_TOKEN
        sync: false
